version: "2"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: yelp_camp
    volumes:
      - ./data/mongodb/db:/data/db
    ports:
      - "27017:27017"